# Generated by Django 4.2.4 on 2023-10-03 05:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("functional_area", models.CharField(max_length=255)),
                ("management_level", models.CharField(max_length=255)),
                ("no_of_openings", models.IntegerField()),
                ("job_type", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("remote_job", models.BooleanField()),
                ("specific_timing", models.BooleanField(default=False)),
                ("specific_time", models.TimeField(blank=True, null=True)),
                (
                    "hard_skills",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "hard_kill_expertise_level",
                    models.IntegerField(
                        verbose_name=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(10),
                        ]
                    ),
                ),
                (
                    "deal_breaker_hard_skill",
                    models.CharField(
                        choices=[(True, "Yes"), (False, "No")], max_length=3
                    ),
                ),
                (
                    "soft_skills",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "soft_skill_expertise_level",
                    models.IntegerField(
                        verbose_name=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(10),
                        ]
                    ),
                ),
                (
                    "language_expertise_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "deal_breaker_language",
                    models.CharField(
                        choices=[(True, "Yes"), (False, "No")], max_length=3
                    ),
                ),
                (
                    "min_months_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "max_months_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                ("include_fresher", models.BooleanField(default=False)),
                (
                    "industry_experience",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "min_years_industry_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "max_years_industry_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MaxLengthValidator(1)]
                    ),
                ),
                (
                    "company_experience",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "min_years_company_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "max_years_company_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MaxLengthValidator(1)]
                    ),
                ),
                ("roles_responsibility", models.TextField(max_length=255)),
                (
                    "min_pay_salary",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "max_pay_salary",
                    models.IntegerField(
                        validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "supplemental_pay",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "benefits",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("notice_period", models.IntegerField()),
                (
                    "blind_hire",
                    models.CharField(
                        choices=[(True, "Yes"), (False, "No")], max_length=3
                    ),
                ),
            ],
        ),
    ]
