# Generated by Django 4.2.4 on 2023-10-05 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("job_title", models.CharField(max_length=255, validators=[()])),
                ("management_level", models.CharField(max_length=255, validators=[()])),
                ("job_type", models.CharField(max_length=255, validators=[()])),
                ("no_of_openings", models.IntegerField(validators=[()])),
                (
                    "days",
                    models.CharField(
                        choices=[
                            ("Monday-Friday", "monday-friday"),
                            ("Monday-Saturday", "monday-saturday"),
                            ("Flexible", "flexible"),
                        ],
                        max_length=17,
                    ),
                ),
                ("specific_timing", models.BooleanField()),
                ("specific_time", models.TimeField()),
                ("flexible_timing", models.BooleanField()),
                ("flexible_time", models.TimeField()),
                ("minimum_years_experience", models.IntegerField(validators=[()])),
                ("maximum_years_experience", models.IntegerField(validators=[()])),
                (
                    "roles_responsibility",
                    models.TextField(max_length=255, validators=[()]),
                ),
                ("minimum_pay", models.IntegerField(validators=[()])),
                ("maximum_pay", models.IntegerField(validators=[()])),
                ("notice_period", models.IntegerField(validators=[()])),
                ("blind_hire", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soft_skill", models.CharField(max_length=255, validators=[()])),
                ("soft_skill_expertise", models.IntegerField(validators=[()])),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soft_skills",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("remote_job", models.BooleanField()),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=255, validators=[()])),
                (
                    "language_expertise",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=15,
                    ),
                ),
                ("deal_breaker", models.BooleanField(default=False)),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255, validators=[()])),
                ("functional_area", models.CharField(max_length=255, validators=[()])),
                ("management_level", models.CharField(max_length=255, validators=[()])),
                ("no_of_openings", models.IntegerField(validators=[()])),
                ("job_type", models.CharField(max_length=255, validators=[()])),
                ("location", models.CharField(max_length=255, validators=[()])),
                ("remote_job", models.BooleanField()),
                ("specific_timing", models.BooleanField(default=False)),
                ("specific_time", models.TimeField(blank=True, null=True)),
                ("flexible_timing", models.BooleanField(default=False)),
                ("flexible_time", models.TimeField(blank=True, null=True)),
                ("hard_skill", models.CharField(max_length=255, validators=[()])),
                ("hard_kill_expertise_level", models.IntegerField(validators=[()])),
                ("deal_breaker_hard_skill", models.BooleanField(default=False)),
                ("soft_skills", models.CharField(max_length=255, validators=[()])),
                ("soft_skill_expertise_level", models.IntegerField(validators=[()])),
                ("language", models.CharField(max_length=255, validators=[()])),
                ("language_expertise_level", models.IntegerField(validators=[()])),
                ("deal_breaker_language", models.BooleanField(default=False)),
                ("min_years_experience", models.IntegerField(validators=[()])),
                ("max_years_experience", models.IntegerField(validators=[()])),
                ("include_fresher", models.BooleanField(default=False)),
                (
                    "industry_experience",
                    models.CharField(max_length=255, validators=[()]),
                ),
                ("min_years_industry_experience", models.IntegerField(validators=[()])),
                ("max_years_industry_experience", models.IntegerField(validators=[()])),
                (
                    "company_experience",
                    models.CharField(max_length=255, validators=[()]),
                ),
                ("min_years_company_experience", models.IntegerField(validators=[()])),
                ("roles_responsibility", models.TextField(validators=[()])),
                ("min_pay_salary", models.IntegerField(validators=[()])),
                ("max_pay_salary", models.IntegerField(validators=[()])),
                ("supplemental_pay", models.CharField(max_length=255, validators=[()])),
                ("benefits", models.CharField(max_length=255, validators=[()])),
                ("notice_period", models.IntegerField(validators=[()])),
                ("blind_hire", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndustryExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(max_length=255, validators=[()])),
                ("minimum_industry_experience", models.IntegerField(validators=[()])),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrys",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hard_skill", models.CharField(max_length=255, validators=[()])),
                ("deal_breaker", models.BooleanField(default=False)),
                ("hard_skill_expertise_level", models.IntegerField(validators=[()])),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_skills",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_pay",
                    models.CharField(
                        choices=[
                            ("Performance Bonus", "performance bonus"),
                            ("Yearly Bonus", "yearly bonus"),
                            ("Quarterly Bonus", "quarterly bonus"),
                            ("Commission", "commission"),
                            ("Overtime Pay", "overtime pay"),
                            ("Shift Allowance", "shift allowance"),
                            ("Joining Bonus", "joining bonus"),
                            ("ESOP", "esop"),
                        ],
                        max_length=255,
                        validators=[()],
                    ),
                ),
                (
                    "job_posts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, validators=[()])),
                ("minimum_company_experience", models.IntegerField(validators=[()])),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companys",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Benefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit",
                    models.CharField(
                        choices=[
                            ("Performance Bonus", "performance bonus"),
                            ("Yearly Bonus", "yearly bonus"),
                            ("Quarterly Bonus", "quarterly bonus"),
                            ("Commission", "commission"),
                            ("Overtime Pay", "overtime pay"),
                            ("Shift Allowance", "shift allowance"),
                            ("Joining Bonus", "joining bonus"),
                            ("ESOP", "esop"),
                        ],
                        max_length=255,
                        validators=[()],
                    ),
                ),
                (
                    "job_posts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="user_app.job_post",
                    ),
                ),
            ],
        ),
    ]
