# Generated by Django 4.2.4 on 2023-10-03 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("functional_area", models.CharField(max_length=255)),
                ("management_level", models.CharField(max_length=255)),
                ("no_of_openings", models.IntegerField()),
                ("job_type", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("remote_job", models.BooleanField()),
                ("specific_timing", models.BooleanField(default=False)),
                ("specific_time", models.TimeField(blank=True, null=True)),
                ("flexible_timing", models.BooleanField(default=False)),
                ("flexible_time", models.TimeField(blank=True, null=True)),
                ("hard_skill", models.CharField(max_length=200)),
                ("hard_kill_expertise_level", models.IntegerField(default=1)),
                ("deal_breaker_hard_skill", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="JobPost",
        ),
    ]
