# Generated by Django 4.2.4 on 2023-10-03 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_jobpost1_delete_jobpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost1",
            name="hard_kill_expertise_level",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(10),
                ]
            ),
        ),
    ]
