# Generated by Django 4.2.4 on 2023-10-03 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_alter_jobpost1_hard_kill_expertise_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("functional_area", models.CharField(max_length=255)),
                ("management_level", models.CharField(max_length=255)),
                ("no_of_openings", models.IntegerField()),
                ("job_type", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("remote_job", models.BooleanField()),
                ("specific_timing", models.BooleanField(default=False)),
                ("specific_time", models.TimeField(blank=True, null=True)),
                ("flexible_timing", models.BooleanField(default=False)),
                ("flexible_time", models.TimeField(blank=True, null=True)),
                ("hard_skill", models.CharField(max_length=200)),
                ("hard_kill_expertise_level", models.IntegerField()),
                ("deal_breaker_hard_skill", models.BooleanField(default=False)),
                ("soft_skills", models.CharField(max_length=200)),
                ("soft_skill_expertise_level", models.IntegerField()),
                ("language", models.CharField(max_length=200)),
                ("language_expertise_level", models.CharField(max_length=200)),
                ("deal_breaker_language", models.BooleanField(default=False)),
                ("min_years_experience", models.IntegerField()),
                ("max_years_experience", models.IntegerField()),
                ("include_fresher", models.BooleanField(default=False)),
                ("industry_experience", models.CharField(max_length=255)),
                ("min_years_industry_experience", models.IntegerField()),
                ("max_years_industry_experience", models.IntegerField()),
                ("company_experience", models.CharField(max_length=255)),
                ("min_years_company_experience", models.IntegerField()),
                ("roles_responsibility", models.TextField(max_length=255)),
                ("min_pay_salary", models.IntegerField()),
                ("max_pay_salary", models.IntegerField()),
                ("supplemental_pay", models.CharField(max_length=255)),
                ("benefits", models.CharField(max_length=255)),
                ("notice_period", models.IntegerField()),
                ("blind_hire", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="JobPost1",
        ),
    ]
