# Generated by Django 4.2.4 on 2023-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_jobpost_delete_jobpost1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="language_expertise_level",
            field=models.IntegerField(),
        ),
    ]
