# Generated by Django 4.2.4 on 2023-10-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0008_alter_benefits_benefit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplementPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplement_pay",
                    models.CharField(
                        choices=[
                            ("Performance Bonus", "performance bonus"),
                            ("Yearly Bonus", "yearly bonus"),
                            ("Quarterly Bonus", "quarterly bonus"),
                            ("Commission", "commission"),
                            ("Overtime Pay", "overtime pay"),
                            ("Shift Allowance", "shift allowance"),
                            ("Joining Bonus", "joining bonus"),
                            ("ESOP", "esop"),
                        ],
                        max_length=255,
                        validators=[()],
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="benefits",
            old_name="job_posts",
            new_name="job_post",
        ),
        migrations.AlterField(
            model_name="benefits",
            name="benefit",
            field=models.CharField(
                choices=[
                    ("Performance Bonus", "performance bonus"),
                    ("Yearly Bonus", "yearly bonus"),
                    ("Quarterly Bonus", "quarterly bonus"),
                    ("Commission", "commission"),
                    ("Overtime Pay", "overtime pay"),
                    ("Shift Allowance", "shift allowance"),
                    ("Joining Bonus", "joining bonus"),
                    ("ESOP", "esop"),
                ],
                max_length=255,
                validators=[()],
            ),
        ),
        migrations.AlterField(
            model_name="companyexperience",
            name="company",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="companyexperience",
            name="minimum_company_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="hardskill",
            name="hard_skill",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="hardskill",
            name="hard_skill_expertise_level",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="industry",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="industryexperience",
            name="minimum_industry_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="job_title",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="job_type",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="management_level",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="maximum_pay",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="maximum_years_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="minimum_pay",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="minimum_years_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="no_of_openings",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="notice_period",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="job_post",
            name="roles_responsibility",
            field=models.TextField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="benefits",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="company_experience",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="functional_area",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="hard_kill_expertise_level",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="hard_skill",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="industry_experience",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_title",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_type",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="language",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="language_expertise_level",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="location",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="management_level",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="max_pay_salary",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="max_years_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="max_years_industry_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="min_pay_salary",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="min_years_company_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="min_years_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="min_years_industry_experience",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="no_of_openings",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="notice_period",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="roles_responsibility",
            field=models.TextField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="soft_skill_expertise_level",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="soft_skills",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="soft_skill",
            field=models.CharField(max_length=255, validators=[()]),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="soft_skill_expertise",
            field=models.IntegerField(validators=[()]),
        ),
        migrations.DeleteModel(
            name="ExtraPay",
        ),
        migrations.AddField(
            model_name="supplementpay",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplement_pays",
                to="user_app.job_post",
            ),
        ),
    ]
