# Generated by Django 4.2.4 on 2023-10-03 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0011_watchlist_avr_rating_watchlist_total_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("functional_area", models.CharField(max_length=255)),
                ("management_level", models.CharField(max_length=255)),
                ("no_of_openings", models.IntegerField()),
                ("job_type", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("remote_job", models.BooleanField()),
                ("specific_timing", models.BooleanField(default=False)),
                ("specific_time", models.TimeField(blank=True, null=True)),
                ("flexible_timing", models.BooleanField(default=False)),
                ("flexible_time", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
