# Generated by Django 4.2.4 on 2023-10-03 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0012_jobpost1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobPost1",
        ),
    ]
